# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'epoching-ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EpochingWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 296)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rawPathButton = QtWidgets.QPushButton(Dialog)
        self.rawPathButton.setObjectName("rawPathButton")
        self.horizontalLayout.addWidget(self.rawPathButton)
        self.rawLine = QtWidgets.QLineEdit(Dialog)
        self.rawLine.setObjectName("rawLine")
        self.horizontalLayout.addWidget(self.rawLine)
        self.rawBox = QtWidgets.QComboBox(Dialog)
        self.rawBox.setObjectName("rawBox")
        self.horizontalLayout.addWidget(self.rawBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotRawButton = QtWidgets.QPushButton(Dialog)
        self.plotRawButton.setObjectName("plotRawButton")
        self.horizontalLayout_2.addWidget(self.plotRawButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mrkPathButton = QtWidgets.QPushButton(Dialog)
        self.mrkPathButton.setObjectName("mrkPathButton")
        self.horizontalLayout_3.addWidget(self.mrkPathButton)
        self.mrkLine = QtWidgets.QLineEdit(Dialog)
        self.mrkLine.setObjectName("mrkLine")
        self.horizontalLayout_3.addWidget(self.mrkLine)
        self.mrkBox = QtWidgets.QComboBox(Dialog)
        self.mrkBox.setObjectName("mrkBox")
        self.horizontalLayout_3.addWidget(self.mrkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.plotMrkButton = QtWidgets.QPushButton(Dialog)
        self.plotMrkButton.setObjectName("plotMrkButton")
        self.verticalLayout_2.addWidget(self.plotMrkButton)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.chooseMrkBox = QtWidgets.QComboBox(Dialog)
        self.chooseMrkBox.setObjectName("chooseMrkBox")
        self.horizontalLayout_4.addWidget(self.chooseMrkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.tmin = QtWidgets.QLineEdit(Dialog)
        self.tmin.setObjectName("tmin")
        self.horizontalLayout_6.addWidget(self.tmin)
        self.tmax = QtWidgets.QLineEdit(Dialog)
        self.tmax.setObjectName("tmax")
        self.horizontalLayout_6.addWidget(self.tmax)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.visuEpochsButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visuEpochsButton.setFont(font)
        self.visuEpochsButton.setObjectName("visuEpochsButton")
        self.horizontalLayout_5.addWidget(self.visuEpochsButton)
        self.saveEpochsButton = QtWidgets.QPushButton(Dialog)
        self.saveEpochsButton.setObjectName("saveEpochsButton")
        self.horizontalLayout_5.addWidget(self.saveEpochsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.verticalLayout_2.setStretch(9, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Raw Data Path"))
        self.rawPathButton.setText(_translate("Dialog", "Path"))
        self.plotRawButton.setText(_translate("Dialog", "Visualize Raw Data"))
        self.label_2.setText(_translate("Dialog", "Markers Path"))
        self.mrkPathButton.setText(_translate("Dialog", "Path"))
        self.plotMrkButton.setText(_translate("Dialog", "Visualize Markers"))
        self.label_3.setText(_translate("Dialog", "Choose marker"))
        self.label_4.setText(_translate("Dialog", "Interval of time around marker"))
        self.visuEpochsButton.setText(_translate("Dialog", "Visualize Epochs"))
        self.saveEpochsButton.setText(_translate("Dialog", "Save Epochs"))
