# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu-ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(668, 636)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MenuWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Time-Frequency-Module/media/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MenuWindow.setWindowIcon(icon)
        MenuWindow.setAutoFillBackground(False)
        MenuWindow.setStyleSheet("")
        MenuWindow.setDocumentMode(False)
        MenuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MenuWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(5, 9, 5, 0)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.upper = QtWidgets.QWidget(self.centralwidget)
        self.upper.setObjectName("upper")
        self.UpperLayout = QtWidgets.QVBoxLayout(self.upper)
        self.UpperLayout.setContentsMargins(0, 0, 0, 0)
        self.UpperLayout.setSpacing(6)
        self.UpperLayout.setObjectName("UpperLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.upper)
        self.verticalGroupBox.setFlat(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.dataLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.dataLayout_2.setObjectName("dataLayout_2")
        self.choosePathLayout = QtWidgets.QHBoxLayout()
        self.choosePathLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.choosePathLayout.setSpacing(10)
        self.choosePathLayout.setObjectName("choosePathLayout")
        self.pathButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pathButton.setMinimumSize(QtCore.QSize(50, 25))
        self.pathButton.setMaximumSize(QtCore.QSize(130, 25))
        self.pathButton.setFlat(False)
        self.pathButton.setObjectName("pathButton")
        self.choosePathLayout.addWidget(self.pathButton)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.choosePathLayout.addWidget(self.lineEdit)
        self.chooseFileType = QtWidgets.QComboBox(self.verticalGroupBox)
        self.chooseFileType.setMinimumSize(QtCore.QSize(100, 25))
        self.chooseFileType.setMaximumSize(QtCore.QSize(100, 25))
        self.chooseFileType.setFrame(False)
        self.chooseFileType.setObjectName("chooseFileType")
        self.choosePathLayout.addWidget(self.chooseFileType)
        self.dataLayout_2.addLayout(self.choosePathLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.informationLabel = QtWidgets.QLabel(self.verticalGroupBox1)
        self.informationLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.informationLabel.setText("")
        self.informationLabel.setObjectName("informationLabel")
        self.verticalLayout_7.addWidget(self.informationLabel)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox1)
        self.verticalGroupBox2 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotData = QtWidgets.QPushButton(self.verticalGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(130)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.plotData.sizePolicy().hasHeightForWidth())
        self.plotData.setSizePolicy(sizePolicy)
        self.plotData.setMinimumSize(QtCore.QSize(50, 25))
        self.plotData.setMaximumSize(QtCore.QSize(5614651, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plotData.setFont(font)
        self.plotData.setFlat(False)
        self.plotData.setObjectName("plotData")
        self.verticalLayout_2.addWidget(self.plotData)
        self.previewLayout = QtWidgets.QVBoxLayout()
        self.previewLayout.setObjectName("previewLayout")
        self.verticalLayout_2.addLayout(self.previewLayout)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox2)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.dataLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addWidget(self.verticalGroupBox)
        self.UpperLayout.addLayout(self.horizontalLayout_8)
        self.mainLayout.addWidget(self.upper)
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setContentsMargins(0, -1, 0, -1)
        self.dataLayout.setSpacing(10)
        self.dataLayout.setObjectName("dataLayout")
        self.wrapper = QtWidgets.QHBoxLayout()
        self.wrapper.setContentsMargins(0, -1, 0, -1)
        self.wrapper.setObjectName("wrapper")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.displayChannel = QtWidgets.QLineEdit(self.verticalGroupBox_2)
        self.displayChannel.setMinimumSize(QtCore.QSize(100, 0))
        self.displayChannel.setObjectName("displayChannel")
        self.horizontalLayout_7.addWidget(self.displayChannel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.pushButton = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(8464654, 25))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_6.addWidget(self.verticalGroupBox_2)
        self.verticalLayout_6.setStretch(0, 1)
        self.wrapper.addLayout(self.verticalLayout_6)
        self.verticalGroupBox_21 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_21.setObjectName("verticalGroupBox_21")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox_21)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xyzPath = QtWidgets.QLineEdit(self.verticalGroupBox_21)
        self.xyzPath.setMinimumSize(QtCore.QSize(100, 0))
        self.xyzPath.setFrame(True)
        self.xyzPath.setObjectName("xyzPath")
        self.horizontalLayout_6.addWidget(self.xyzPath)
        self.electrodeMontage = QtWidgets.QComboBox(self.verticalGroupBox_21)
        self.electrodeMontage.setMinimumSize(QtCore.QSize(100, 25))
        self.electrodeMontage.setMaximumSize(QtCore.QSize(200, 25))
        self.electrodeMontage.setFrame(False)
        self.electrodeMontage.setObjectName("electrodeMontage")
        self.horizontalLayout_6.addWidget(self.electrodeMontage)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.showMontageButton = QtWidgets.QPushButton(self.verticalGroupBox_21)
        self.showMontageButton.setObjectName("showMontageButton")
        self.verticalLayout_4.addWidget(self.showMontageButton)
        self.wrapper.addWidget(self.verticalGroupBox_21)
        self.wrapper.setStretch(0, 1)
        self.wrapper.setStretch(1, 1)
        self.dataLayout.addLayout(self.wrapper)
        self.dataLayout.setStretch(0, 1)
        self.mainLayout.addLayout(self.dataLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.psdTab = QtWidgets.QWidget()
        self.psdTab.setObjectName("psdTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.psdTab)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.psdTab)
        self.verticalWidget.setObjectName("verticalWidget")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.tabLayout1.setContentsMargins(0, 0, 0, 0)
        self.tabLayout1.setSpacing(6)
        self.tabLayout1.setObjectName("tabLayout1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodLabel = QtWidgets.QLabel(self.verticalWidget)
        self.methodLabel.setMinimumSize(QtCore.QSize(160, 25))
        self.methodLabel.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel.setFont(font)
        self.methodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout.addWidget(self.methodLabel)
        self.psdMethod = QtWidgets.QComboBox(self.verticalWidget)
        self.psdMethod.setMinimumSize(QtCore.QSize(100, 25))
        self.psdMethod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethod.setAccessibleName("")
        self.psdMethod.setCurrentText("")
        self.psdMethod.setFrame(False)
        self.psdMethod.setObjectName("psdMethod")
        self.horizontalLayout.addWidget(self.psdMethod)
        spacerItem = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.tabLayout1.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setMinimumSize(QtCore.QSize(160, 25))
        self.label_2.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.psdParametersLine = QtWidgets.QLineEdit(self.verticalWidget)
        self.psdParametersLine.setMinimumSize(QtCore.QSize(100, 25))
        self.psdParametersLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdParametersLine.setFrame(True)
        self.psdParametersLine.setObjectName("psdParametersLine")
        self.horizontalLayout_2.addWidget(self.psdParametersLine)
        self.psdParametersButton = QtWidgets.QPushButton(self.verticalWidget)
        self.psdParametersButton.setMinimumSize(QtCore.QSize(160, 25))
        self.psdParametersButton.setMaximumSize(QtCore.QSize(130, 25))
        self.psdParametersButton.setObjectName("psdParametersButton")
        self.horizontalLayout_2.addWidget(self.psdParametersButton)
        self.tabLayout1.addLayout(self.horizontalLayout_2)
        self.psdParametersText = QtWidgets.QTextEdit(self.verticalWidget)
        self.psdParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.psdParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.psdParametersText.setLineWidth(1)
        self.psdParametersText.setObjectName("psdParametersText")
        self.tabLayout1.addWidget(self.psdParametersText)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.psdButton = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.psdButton.setFont(font)
        self.psdButton.setCheckable(False)
        self.psdButton.setObjectName("psdButton")
        self.horizontalLayout_5.addWidget(self.psdButton)
        self.savePsdButton = QtWidgets.QPushButton(self.verticalWidget)
        self.savePsdButton.setObjectName("savePsdButton")
        self.horizontalLayout_5.addWidget(self.savePsdButton)
        self.tabLayout1.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.verticalWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.tabWidget.addTab(self.psdTab, "")
        self.tfrTab = QtWidgets.QWidget()
        self.tfrTab.setObjectName("tfrTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tfrTab)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.methodLabel_3 = QtWidgets.QLabel(self.tfrTab)
        self.methodLabel_3.setMinimumSize(QtCore.QSize(160, 25))
        self.methodLabel_3.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel_3.setFont(font)
        self.methodLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel_3.setObjectName("methodLabel_3")
        self.horizontalLayout_3.addWidget(self.methodLabel_3)
        self.tfrMethodBox = QtWidgets.QComboBox(self.tfrTab)
        self.tfrMethodBox.setMinimumSize(QtCore.QSize(150, 25))
        self.tfrMethodBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrMethodBox.setAccessibleName("")
        self.tfrMethodBox.setCurrentText("")
        self.tfrMethodBox.setObjectName("tfrMethodBox")
        self.horizontalLayout_3.addWidget(self.tfrMethodBox)
        spacerItem1 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tfrTab)
        self.label.setMinimumSize(QtCore.QSize(160, 25))
        self.label.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.tfrParametersLine = QtWidgets.QLineEdit(self.tfrTab)
        self.tfrParametersLine.setMinimumSize(QtCore.QSize(300, 25))
        self.tfrParametersLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrParametersLine.setFrame(True)
        self.tfrParametersLine.setObjectName("tfrParametersLine")
        self.horizontalLayout_4.addWidget(self.tfrParametersLine)
        self.tfrParametersButton = QtWidgets.QPushButton(self.tfrTab)
        self.tfrParametersButton.setMinimumSize(QtCore.QSize(160, 25))
        self.tfrParametersButton.setMaximumSize(QtCore.QSize(160, 25))
        self.tfrParametersButton.setObjectName("tfrParametersButton")
        self.horizontalLayout_4.addWidget(self.tfrParametersButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tfrParametersText = QtWidgets.QTextEdit(self.tfrTab)
        self.tfrParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfrParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tfrParametersText.setObjectName("tfrParametersText")
        self.verticalLayout.addWidget(self.tfrParametersText)
        self.tfrButton = QtWidgets.QPushButton(self.tfrTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tfrButton.setFont(font)
        self.tfrButton.setObjectName("tfrButton")
        self.verticalLayout.addWidget(self.tfrButton)
        self.tabWidget.addTab(self.tfrTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 1)
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuInformations = QtWidgets.QMenu(self.menubar)
        self.menuInformations.setObjectName("menuInformations")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)
        self.actionHow_To = QtWidgets.QAction(MenuWindow)
        self.actionHow_To.setObjectName("actionHow_To")
        self.actionAbout_Parameters = QtWidgets.QAction(MenuWindow)
        self.actionAbout_Parameters.setObjectName("actionAbout_Parameters")
        self.actionConvert_Raw_to_Epochs = QtWidgets.QAction(MenuWindow)
        self.actionConvert_Raw_to_Epochs.setObjectName("actionConvert_Raw_to_Epochs")
        self.actionICA_Toolbox = QtWidgets.QAction(MenuWindow)
        self.actionICA_Toolbox.setObjectName("actionICA_Toolbox")
        self.actionContact_us = QtWidgets.QAction(MenuWindow)
        self.actionContact_us.setObjectName("actionContact_us")
        self.actionCampus_Biotech = QtWidgets.QAction(MenuWindow)
        self.actionCampus_Biotech.setObjectName("actionCampus_Biotech")
        self.actionAbout_the_project = QtWidgets.QAction(MenuWindow)
        self.actionAbout_the_project.setObjectName("actionAbout_the_project")
        self.actionContribute = QtWidgets.QAction(MenuWindow)
        self.actionContribute.setObjectName("actionContribute")
        self.menuHelp.addAction(self.actionHow_To)
        self.menuHelp.addAction(self.actionAbout_Parameters)
        self.menuTools.addAction(self.actionConvert_Raw_to_Epochs)
        self.menuTools.addAction(self.actionICA_Toolbox)
        self.menuInformations.addAction(self.actionCampus_Biotech)
        self.menuInformations.addAction(self.actionAbout_the_project)
        self.menuInformations.addAction(self.actionContribute)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuInformations.menuAction())

        self.retranslateUi(MenuWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "PSD Frequency Visualizer"))
        self.verticalGroupBox.setTitle(_translate("MenuWindow", "Data"))
        self.pathButton.setText(_translate("MenuWindow", "Path"))
        self.verticalGroupBox1.setTitle(_translate("MenuWindow", "Informations"))
        self.verticalGroupBox2.setTitle(_translate("MenuWindow", "Preview"))
        self.plotData.setText(_translate("MenuWindow", " Open Interactive Window"))
        self.verticalGroupBox_2.setTitle(_translate("MenuWindow", "Channels"))
        self.pushButton.setText(_translate("MenuWindow", "Select Channels"))
        self.verticalGroupBox_21.setTitle(_translate("MenuWindow", "Electrode Convention"))
        self.showMontageButton.setText(_translate("MenuWindow", "See Montage"))
        self.methodLabel.setText(_translate("MenuWindow", "Method"))
        self.label_2.setText(_translate("MenuWindow", "Parameters"))
        self.psdParametersButton.setText(_translate("MenuWindow", "Import "))
        self.psdButton.setText(_translate("MenuWindow", "Visualize PSD"))
        self.savePsdButton.setText(_translate("MenuWindow", "Save PSD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.psdTab), _translate("MenuWindow", "Power Spectrum Density "))
        self.methodLabel_3.setText(_translate("MenuWindow", "Method"))
        self.label.setText(_translate("MenuWindow", "Parameters"))
        self.tfrParametersButton.setText(_translate("MenuWindow", "Import"))
        self.tfrButton.setText(_translate("MenuWindow", "Visualize TFR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tfrTab), _translate("MenuWindow", "Time-Frequency Representation"))
        self.menuHelp.setTitle(_translate("MenuWindow", "Help"))
        self.menuTools.setTitle(_translate("MenuWindow", "Other Softwares "))
        self.menuInformations.setTitle(_translate("MenuWindow", "Informations"))
        self.actionHow_To.setText(_translate("MenuWindow", "How To Use ? "))
        self.actionAbout_Parameters.setText(_translate("MenuWindow", "About Parameters"))
        self.actionConvert_Raw_to_Epochs.setText(_translate("MenuWindow", "Raw to Epochs Converter"))
        self.actionICA_Toolbox.setText(_translate("MenuWindow", "ICA Toolbox"))
        self.actionContact_us.setText(_translate("MenuWindow", "Contact us !"))
        self.actionCampus_Biotech.setText(_translate("MenuWindow", "About Fondation Campus Biotech Geneva"))
        self.actionAbout_the_project.setText(_translate("MenuWindow", "About the Human Neuroscience Platform"))
        self.actionContribute.setText(_translate("MenuWindow", "Contribute"))
