# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu-v2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreprocessWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(663, 595)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MenuWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Time-Frequency-Module/media/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MenuWindow.setWindowIcon(icon)
        MenuWindow.setAutoFillBackground(False)
        MenuWindow.setStyleSheet("")
        MenuWindow.setDocumentMode(False)
        MenuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MenuWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(5, 9, 5, 0)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.upper = QtWidgets.QWidget(self.centralwidget)
        self.upper.setObjectName("upper")
        self.UpperLayout = QtWidgets.QVBoxLayout(self.upper)
        self.UpperLayout.setContentsMargins(0, 0, 0, 0)
        self.UpperLayout.setSpacing(6)
        self.UpperLayout.setObjectName("UpperLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalTabWidget = QtWidgets.QTabWidget(self.upper)
        self.verticalTabWidget.setTabsClosable(False)
        self.verticalTabWidget.setObjectName("verticalTabWidget")
        self.verticalTabWidgetPage1 = QtWidgets.QWidget()
        self.verticalTabWidgetPage1.setObjectName("verticalTabWidgetPage1")
        self.dataLayout_2 = QtWidgets.QVBoxLayout(self.verticalTabWidgetPage1)
        self.dataLayout_2.setObjectName("dataLayout_2")
        self.choosePathLayout = QtWidgets.QHBoxLayout()
        self.choosePathLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.choosePathLayout.setSpacing(10)
        self.choosePathLayout.setObjectName("choosePathLayout")
        self.pathButtonData = QtWidgets.QPushButton(self.verticalTabWidgetPage1)
        self.pathButtonData.setMinimumSize(QtCore.QSize(50, 25))
        self.pathButtonData.setMaximumSize(QtCore.QSize(130, 25))
        self.pathButtonData.setFlat(False)
        self.pathButtonData.setObjectName("pathButtonData")
        self.choosePathLayout.addWidget(self.pathButtonData)
        self.pathLineData = QtWidgets.QLineEdit(self.verticalTabWidgetPage1)
        self.pathLineData.setMinimumSize(QtCore.QSize(100, 25))
        self.pathLineData.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pathLineData.setFrame(True)
        self.pathLineData.setReadOnly(True)
        self.pathLineData.setObjectName("pathLineData")
        self.choosePathLayout.addWidget(self.pathLineData)
        self.dataFilesBox = QtWidgets.QComboBox(self.verticalTabWidgetPage1)
        self.dataFilesBox.setMinimumSize(QtCore.QSize(100, 25))
        self.dataFilesBox.setMaximumSize(QtCore.QSize(464684, 25))
        self.dataFilesBox.setFrame(False)
        self.dataFilesBox.setObjectName("dataFilesBox")
        self.choosePathLayout.addWidget(self.dataFilesBox)
        self.choosePathLayout.setStretch(0, 1)
        self.choosePathLayout.setStretch(1, 4)
        self.choosePathLayout.setStretch(2, 2)
        self.dataLayout_2.addLayout(self.choosePathLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.verticalTabWidgetPage1)
        self.verticalGroupBox.setCheckable(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.informationLabel = QtWidgets.QLabel(self.verticalGroupBox)
        self.informationLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.informationLabel.setText("")
        self.informationLabel.setObjectName("informationLabel")
        self.verticalLayout_7.addWidget(self.informationLabel)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.verticalTabWidgetPage1)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.previewLayout = QtWidgets.QVBoxLayout()
        self.previewLayout.setObjectName("previewLayout")
        self.verticalLayout_2.addLayout(self.previewLayout)
        self.initDataButton = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.initDataButton.setObjectName("initDataButton")
        self.verticalLayout_2.addWidget(self.initDataButton)
        self.horizontalLayout_9.addWidget(self.verticalGroupBox1)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.dataLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalTabWidget.addTab(self.verticalTabWidgetPage1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathButtonMRK = QtWidgets.QPushButton(self.tab)
        self.pathButtonMRK.setObjectName("pathButtonMRK")
        self.horizontalLayout_3.addWidget(self.pathButtonMRK)
        self.pathLineMRK = QtWidgets.QLineEdit(self.tab)
        self.pathLineMRK.setReadOnly(True)
        self.pathLineMRK.setObjectName("pathLineMRK")
        self.horizontalLayout_3.addWidget(self.pathLineMRK)
        self.MRKTypeCombo = QtWidgets.QComboBox(self.tab)
        self.MRKTypeCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.MRKTypeCombo.setObjectName("MRKTypeCombo")
        self.horizontalLayout_3.addWidget(self.MRKTypeCombo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.plotButtonMRK = QtWidgets.QPushButton(self.tab)
        self.plotButtonMRK.setObjectName("plotButtonMRK")
        self.verticalLayout_8.addWidget(self.plotButtonMRK)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalTabWidget.addTab(self.tab, "")
        self.horizontalLayout_8.addWidget(self.verticalTabWidget)
        self.UpperLayout.addLayout(self.horizontalLayout_8)
        self.mainLayout.addWidget(self.upper)
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setContentsMargins(0, -1, 0, -1)
        self.dataLayout.setSpacing(10)
        self.dataLayout.setObjectName("dataLayout")
        self.wrapper = QtWidgets.QHBoxLayout()
        self.wrapper.setContentsMargins(0, -1, 0, -1)
        self.wrapper.setObjectName("wrapper")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.filterPanel = QtWidgets.QGroupBox(self.centralwidget)
        self.filterPanel.setStyleSheet("")
        self.filterPanel.setCheckable(True)
        self.filterPanel.setObjectName("filterPanel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.filterPanel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.filterPanel)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.lowFilter = QtWidgets.QLineEdit(self.filterPanel)
        self.lowFilter.setMaxLength(4)
        self.lowFilter.setObjectName("lowFilter")
        self.horizontalLayout_10.addWidget(self.lowFilter)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.filterPanel)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.highFilter = QtWidgets.QLineEdit(self.filterPanel)
        self.highFilter.setMaxLength(4)
        self.highFilter.setFrame(True)
        self.highFilter.setObjectName("highFilter")
        self.horizontalLayout_11.addWidget(self.highFilter)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.filterPanel)
        self.verticalLayout_6.setStretch(0, 1)
        self.wrapper.addLayout(self.verticalLayout_6)
        self.wrapper.setStretch(0, 1)
        self.dataLayout.addLayout(self.wrapper)
        self.refPanel = QtWidgets.QGroupBox(self.centralwidget)
        self.refPanel.setStyleSheet("")
        self.refPanel.setCheckable(True)
        self.refPanel.setObjectName("refPanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.refPanel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.refBox = QtWidgets.QComboBox(self.refPanel)
        self.refBox.setObjectName("refBox")
        self.verticalLayout_3.addWidget(self.refBox)
        self.dataLayout.addWidget(self.refPanel)
        self.dataLayout.setStretch(0, 1)
        self.dataLayout.setStretch(1, 1)
        self.mainLayout.addLayout(self.dataLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.interpPanel = QtWidgets.QGroupBox(self.centralwidget)
        self.interpPanel.setStyleSheet("")
        self.interpPanel.setCheckable(True)
        self.interpPanel.setObjectName("interpPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.interpPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.interpPanel)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.interpBox = QtWidgets.QComboBox(self.interpPanel)
        self.interpBox.setObjectName("interpBox")
        self.horizontalLayout_6.addWidget(self.interpBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.interpPanel)
        self.montagePanel = QtWidgets.QGroupBox(self.centralwidget)
        self.montagePanel.setCheckable(True)
        self.montagePanel.setObjectName("montagePanel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.montagePanel)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.montageBox = QtWidgets.QComboBox(self.montagePanel)
        self.montageBox.setMinimumSize(QtCore.QSize(100, 25))
        self.montageBox.setMaximumSize(QtCore.QSize(6516351, 25))
        self.montageBox.setFrame(False)
        self.montageBox.setObjectName("montageBox")
        self.verticalLayout_4.addWidget(self.montageBox)
        self.showMontageButton = QtWidgets.QPushButton(self.montagePanel)
        self.showMontageButton.setObjectName("showMontageButton")
        self.verticalLayout_4.addWidget(self.showMontageButton)
        self.horizontalLayout.addWidget(self.montagePanel)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.plotDataButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(130)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.plotDataButton.sizePolicy().hasHeightForWidth())
        self.plotDataButton.setSizePolicy(sizePolicy)
        self.plotDataButton.setMinimumSize(QtCore.QSize(50, 25))
        self.plotDataButton.setMaximumSize(QtCore.QSize(5614651, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plotDataButton.setFont(font)
        self.plotDataButton.setFlat(False)
        self.plotDataButton.setObjectName("plotDataButton")
        self.mainLayout.addWidget(self.plotDataButton)
        self.cutCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.cutCheck.setObjectName("cutCheck")
        self.mainLayout.addWidget(self.cutCheck)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveDataButton.setObjectName("saveDataButton")
        self.horizontalLayout_2.addWidget(self.saveDataButton)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuInformations = QtWidgets.QMenu(self.menubar)
        self.menuInformations.setObjectName("menuInformations")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)
        self.actionHow_To = QtWidgets.QAction(MenuWindow)
        self.actionHow_To.setObjectName("actionHow_To")
        self.actionAbout_Parameters = QtWidgets.QAction(MenuWindow)
        self.actionAbout_Parameters.setObjectName("actionAbout_Parameters")
        self.actionConvert_Raw_to_Epochs = QtWidgets.QAction(MenuWindow)
        self.actionConvert_Raw_to_Epochs.setObjectName("actionConvert_Raw_to_Epochs")
        self.actionICA_Toolbox = QtWidgets.QAction(MenuWindow)
        self.actionICA_Toolbox.setObjectName("actionICA_Toolbox")
        self.actionContact_us = QtWidgets.QAction(MenuWindow)
        self.actionContact_us.setObjectName("actionContact_us")
        self.actionCampus_Biotech = QtWidgets.QAction(MenuWindow)
        self.actionCampus_Biotech.setObjectName("actionCampus_Biotech")
        self.actionAbout_the_project = QtWidgets.QAction(MenuWindow)
        self.actionAbout_the_project.setObjectName("actionAbout_the_project")
        self.actionContribute = QtWidgets.QAction(MenuWindow)
        self.actionContribute.setObjectName("actionContribute")
        self.menuHelp.addAction(self.actionHow_To)
        self.menuHelp.addAction(self.actionAbout_Parameters)
        self.menuTools.addAction(self.actionConvert_Raw_to_Epochs)
        self.menuTools.addAction(self.actionICA_Toolbox)
        self.menuInformations.addAction(self.actionCampus_Biotech)
        self.menuInformations.addAction(self.actionAbout_the_project)
        self.menuInformations.addAction(self.actionContribute)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuInformations.menuAction())

        self.retranslateUi(MenuWindow)
        self.verticalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "PSD Frequency Visualizer"))
        self.pathButtonData.setText(_translate("MenuWindow", "Path"))
        self.verticalGroupBox.setTitle(_translate("MenuWindow", "Informations"))
        self.verticalGroupBox1.setTitle(_translate("MenuWindow", "Preview"))
        self.initDataButton.setText(_translate("MenuWindow", "Raw Data Preview - Bad Channels Selection"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.verticalTabWidgetPage1), _translate("MenuWindow", "Data"))
        self.pathButtonMRK.setText(_translate("MenuWindow", "Path"))
        self.plotButtonMRK.setText(_translate("MenuWindow", "Visualize Markers"))
        self.label.setText(_translate("MenuWindow", "Choose Marker"))
        self.label_2.setText(_translate("MenuWindow", "Time around marker"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.tab), _translate("MenuWindow", "Markers"))
        self.filterPanel.setTitle(_translate("MenuWindow", "Filters"))
        self.label_4.setText(_translate("MenuWindow", "Low (Hz)"))
        self.label_5.setText(_translate("MenuWindow", "High (Hz)"))
        self.refPanel.setTitle(_translate("MenuWindow", "Reference"))
        self.interpPanel.setTitle(_translate("MenuWindow", "Interpolate Bad Channels"))
        self.label_6.setText(_translate("MenuWindow", "Type"))
        self.montagePanel.setTitle(_translate("MenuWindow", "Electrode Convention"))
        self.showMontageButton.setText(_translate("MenuWindow", "See Montage"))
        self.plotDataButton.setText(_translate("MenuWindow", "Processed Data Preview"))
        self.cutCheck.setText(_translate("MenuWindow", "Cut Into Epochs"))
        self.saveDataButton.setText(_translate("MenuWindow", "Save"))
        self.menuHelp.setTitle(_translate("MenuWindow", "Help"))
        self.menuTools.setTitle(_translate("MenuWindow", "Other Softwares "))
        self.menuInformations.setTitle(_translate("MenuWindow", "Informations"))
        self.actionHow_To.setText(_translate("MenuWindow", "How To Use ? "))
        self.actionAbout_Parameters.setText(_translate("MenuWindow", "About Parameters"))
        self.actionConvert_Raw_to_Epochs.setText(_translate("MenuWindow", "Raw to Epochs Converter"))
        self.actionICA_Toolbox.setText(_translate("MenuWindow", "ICA Toolbox"))
        self.actionContact_us.setText(_translate("MenuWindow", "Contact us !"))
        self.actionCampus_Biotech.setText(_translate("MenuWindow", "About Fondation Campus Biotech Geneva"))
        self.actionAbout_the_project.setText(_translate("MenuWindow", "About the Human Neuroscience Platform"))
        self.actionContribute.setText(_translate("MenuWindow", "Contribute"))
